version: 1 
runtime: python27
api_version: 1 
threadsafe: true

handlers:
- url: /bootstrap33
  static_dir: bootstrap33

- url: /startbootstrap-grayscale-1.0.5
  static_dir: startbootstrap-grayscale-1.0.5

- url: /jquery
  static_dir: jquery

- url: /assets
  static_dir: assets

#- url: /task
#  script: main.app
#  login: admin

- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

